// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";
import { getMigrationDatabaseUrlFromEnv } from "./src/config/database.config";

const envFile = config({ path: ".env" }).parsed ?? {};
const localEnvFile = config({ path: ".env.local" }).parsed ?? {};
const databaseEnv = { ...process.env, ...envFile, ...localEnvFile };

if (!envFile.DATABASE_URL && envFile.DB_HOST) {
  delete databaseEnv.DATABASE_URL;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getMigrationDatabaseUrlFromEnv(databaseEnv),
  },
});
